language: java
sudo: required
dist: trusty

script: ant -Divy.logging=default test

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-unlimited-jce-policy
      - haveged

before_install:
  - sudo service haveged start

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8

cache:
  apt: true
  directories:
    - $HOME/.ivy2

notifications:
  email: false

branches:
  only:
  - develop
