version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - quotidian-ennui
      - aaron-mcgrath-adp
      - higgyfella
      - sebastien-belin-adp