name: Java CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Set up JDK 11
      uses: actions/setup-java@v2.4.0
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Gradle Wrapper Cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
    - name: Gradle Dependencies Cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          ${{ runner.os }}-gradle-cache-
    - name: Gradle Test
      run: |
        echo "default.jdbc.storedproc.tests.enabled=false" >> ./interlok-core/build.properties
        echo "junit.jms.tests.enabled=false" >> ./interlok-core/build.properties
        ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
    - name: codecov.io
      uses: codecov/codecov-action@v2.1.0